# Spyke CLI installer for Windows (PowerShell).
#
#   irm https://get.spykeautomation.com/install.ps1 | iex
#
# Downloads the latest spyke.exe into %LOCALAPPDATA%\Programs\Spyke, adds it to
# the user PATH, and installs PowerShell tab-completion. Re-run any time to
# upgrade. Override the release source with $env:SPYKE_RELEASE_BASE.

$ErrorActionPreference = 'Stop'

$RepoReleases = if ($env:SPYKE_RELEASE_BASE) { $env:SPYKE_RELEASE_BASE } else {
    'https://github.com/spykeautomation/spyke/releases/latest/download'
}

# Pick the right architecture build.
$arch = if ([Environment]::Is64BitOperatingSystem) {
    if ($env:PROCESSOR_ARCHITECTURE -eq 'ARM64') { 'arm64' } else { 'amd64' }
} else { 'amd64' }
$asset = "spyke_windows_$arch.exe"

$installDir = Join-Path $env:LOCALAPPDATA 'Programs\Spyke'
$target = Join-Path $installDir 'spyke.exe'

Write-Host "Installing Spyke CLI ($arch) to $installDir ..."
New-Item -ItemType Directory -Force -Path $installDir | Out-Null

# Download the binary.
$url = "$RepoReleases/$asset"
Write-Host "Downloading $url"
Invoke-WebRequest -Uri $url -OutFile $target -UseBasicParsing

# Add to the user PATH if it isn't already there.
$userPath = [Environment]::GetEnvironmentVariable('Path', 'User')
if (($userPath -split ';') -notcontains $installDir) {
    Write-Host "Adding $installDir to your PATH"
    [Environment]::SetEnvironmentVariable('Path', "$userPath;$installDir", 'User')
    $env:Path = "$env:Path;$installDir"
}

# Install PowerShell tab-completion (generated by the binary itself).
try {
    $profileDir = Split-Path -Parent $PROFILE
    New-Item -ItemType Directory -Force -Path $profileDir | Out-Null
    $completionPath = Join-Path $profileDir 'spyke.completion.ps1'
    & $target completion powershell | Out-File -FilePath $completionPath -Encoding utf8
    if (-not (Select-String -Path $PROFILE -Pattern 'spyke.completion.ps1' -SimpleMatch -Quiet -ErrorAction SilentlyContinue)) {
        Add-Content -Path $PROFILE -Value ". `"$completionPath`""
    }
    Write-Host "Installed PowerShell completion."
} catch {
    Write-Warning "Skipped completion setup: $($_.Exception.Message)"
}

Write-Host ""
Write-Host "Spyke CLI installed. Open a new terminal, then run:  spyke login"
& $target --version
